<?php

/**
 * @file
 * The module file.
 *
 * Implements main module hooks.
 */

define('VUEJS_PATH', drupal_get_path('module', 'vue_js'));
define('VUEJS_LIBRARY', 'vue_js');
define('VUEJS_NAME', 'Vue.js');
define('VUEJS_URL', 'https://vue_js.org/');
define('VUEJS_DOWNLOAD_URL', 'https://vuejs.org/js/vue.min.js');
define('VUEJS_VERSION_DEV', 'vue.js');
define('VUEJS_VERSION_MIN', 'vue.min.js');
define('VUEJS_VERSION_CDN', 'cdn');
define('VUEJS_CDN_URL', '//unpkg.com/vue');

/**
 * Implements hook_permission().
 */
function vue_js_permission() {
  return array(
    'vue_js configuration' => array(
      'title'           => t('Configure Vue.js'),
      'description'     => t('Allow users to configure Vue.js module'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function vue_js_menu() {
  return array(
    'admin/config/development/vue_js' => array(
      'title'            => VUEJS_NAME,
      'description'      => 'Configure settings related to the Vue.js library.',
      'file'             => 'includes/vue_js.admin.inc',
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('vue_js_page_callback'),
      'access arguments' => array('vue_js configuration'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function vue_js_libraries_info() {
  $ver = variable_get('vue_js_version', VUEJS_VERSION_CDN);
  $ver = $ver == VUEJS_VERSION_DEV ? VUEJS_VERSION_DEV : VUEJS_VERSION_MIN;

  return array(
    VUEJS_LIBRARY => array(
      'name'              => VUEJS_NAME,
      'vendor url'        => VUEJS_URL,
      'download url'      => VUEJS_DOWNLOAD_URL,
      'version arguments' => array(
        'file'    => "vue/$ver",
        'pattern' => '/v(\d+\.\d+\.\d+)/',
        'lines'   => 2,
      ),
      'files'             => array(
        'js' => array(
          "vue/$ver",
        ),
      ),
    ),
  );
}

/**
 * Implements hook_library().
 */
function vue_js_library() {
  $library = libraries_detect(VUEJS_LIBRARY);

  $libraries[VUEJS_LIBRARY] = array(
    'title'   => $library['name'],
    'website' => $library['vendor url'],
    'version' => $library['version'],
    'js'      => array(
      $library['library path'] . '/' . key($library['files']['js']) => array(
        'scope' => 'footer',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_library_alter().
 */
function vue_js_library_alter(&$javascript, $module) {

  // Replace library to CDN version
  if (variable_get('vue_js_version', VUEJS_VERSION_CDN) == VUEJS_VERSION_CDN) {
    $javascript[VUEJS_LIBRARY]['js']['sites/all/libraries/vue_js/vue/vue.min.js']['data'] = VUEJS_CDN_URL;
    $javascript[VUEJS_LIBRARY]['js']['sites/all/libraries/vue_js/vue/vue.min.js']['type'] = 'external';
    $javascript[VUEJS_LIBRARY]['version'] = '2';
  }
}
